query getUser($login : String!) {
  user(login : $login) {
    login
    name
    avatarUrl
    bio
    following {
      totalCount
    }
    followers {
      totalCount
    }
    contributionsCollection{
      totalCommitContributions
    }
    starredRepositories {
      totalCount
    }
    repositories(first: 10, privacy: PUBLIC, orderBy: {field: UPDATED_AT, direction: DESC}) {
      totalCount
      edges {
        node {
          name
          description
          url
          updatedAt
          stargazerCount
          forkCount
          primaryLanguage{
            name
            color
          }
        }
      }
    }
  }
}